server:
  ssl:
    certificate: docker/keycloak/certs/localhost.pem
    certificate-private-key: docker/keycloak/certs/localhost-key.pem

spring:
  jpa:
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:18080/realms/tsas/protocol/openid-connect/certs

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} %-5level [%X{correlationId:-}] %logger{36} - %msg%n"

tsas:
  cors:
    allowed-origins:
      - "http://localhost:4200"
      - "https://localhost:4200"
